Use 'build-base' so the core18 snap is not required when installing
canonical/multipass-sshfs pull request #2
Opened 2019-07-26 14:57 UTC by townsend2010

2019-07-26 15:40 UTC, Saviq requested changes
We can't be a `type: base` snap, as that would mean someone would be able to do `base: multipass-sshfs` in their snap, which doesn't make sense.

Snapcraft might not support `base: bare; build-base: core18` just yet, but we should be able to manually amend the snap metadata before uploading to the store while we wait for this to be supported.

2019-07-26 15:40 UTC, Saviq commented on snapcraft.yaml
> +type: base
We should instead have this:

```suggestion
base: bare
```

2019-07-26 17:47 UTC, townsend2010 commented
So, I tried directly modifying the `snap.yaml` file in the unsquashed snap.

With `base: bare` and then try to install the snap:
```
error: cannot perform the following tasks:
- Ensure prerequisites for "multipass-sshfs" are available (no snap revision available as specified)
```

With `base: none` and then try to install the snap:
```
error: cannot perform the following tasks:
- Ensure prerequisites for "multipass-sshfs" are available (snap not found)
```

I think at this point, the only way to build a snap without requiring the base is to make it a base snap itself, and as has been said, that's not really what we want.

2019-07-27 20:46 UTC, Saviq commented
> ```
> error: cannot perform the following tasks:
> - Ensure prerequisites for "multipass-sshfs" are available (no snap revision available as specified)
> ```

This is fine! It's just that the `bare` snap is only available on `edge` today.

```
$ snap info bare
…
channels:
  stable:    –                      
  candidate: –                      
  beta:      –                      
  edge:      1.0 2017-07-26 (5) 4kB -
```

We just need to bring the bare snap with us as well. Which was the plan all along if we want to ensure offline operation.

Oh and just realized, if we bring the snap along with its assertion (`snap download <snap>`), it will know straight away that it can upgrade from the store :)

2020-01-29 21:16 UTC, townsend2010 commented
This is no longer needed so closing.

2020-01-29 21:16 UTC, closed without merging